# Generated by Django 4.2.5 on 2023-10-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('HO', 'Housing'), ('FO', 'Food'), ('TR', 'Transport'), ('TRAV', 'Travel'), ('HE', 'Health'), ('ED', 'Education'), ('SH', 'Shopping'), ('CL', 'Clothing'), ('TAX', 'Tax'), ('LE', 'Leisure'), ('GIF', 'Gifts/Donations'), ('WO', 'Work')], max_length=4, verbose_name='Category')),
                ('payment_method', models.CharField(choices=[('CR', 'Credit Card'), ('DE', 'Debit')], max_length=2, verbose_name='Payment Method')),
                ('credit_card', models.CharField(blank=True, max_length=50, null=True, verbose_name='Credit Card')),
                ('month', models.PositiveIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], verbose_name='Month')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Expenditure',
                'verbose_name_plural': 'Expenditures',
                'ordering': ['-year', '-month', 'category'],
            },
        ),
    ]
