# Generated by Django 4.2.5 on 2023-10-01 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0003_alter_expenditure_month'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Revenue',
        ),
    ]
