# Generated by Django 4.2.5 on 2023-10-01 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0004_delete_revenue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expenditure',
        ),
    ]
